# Generated by Django 3.1.7 on 2021-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210310_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='text',
            field=models.CharField(default='text', max_length=200),
            preserve_default=False,
        ),
    ]
